spring:
  application:
    name: dubbo-provider
dubbo:
#  protocol:
#    name: dubbo
#    # -1:不指定端口号，让系统生成
#    port: -1
#  registry:
#    address: nacos://localhost:8848
    # 多注册中心配置
  protocols:
    #Netty
    dubbo:
      name: dubbo
      port: -1
    #Jetty(配置了rest协议)
    rest:
      name: rest
      port: 8888
      server: jetty
  registries:
    shanghai:
      address: nacos://localhost:8848
    hunan:
      address: nacos://localhost:8848